### ISSUE TITLE
error by the example command you supported "python3 scripts/main.py configs/oxnas.cfg"

### ISSUE THREAD

**Issue by minifish120** [valour01/ecmo#1]
as the title ,when i tried this project by running the example you supported "python3 scripts/main.py configs/oxnas.cfg", it reported the following error:
irq_domain_xlate_onetwocell_addrs : 0xd54 : 0xc0056290
Generating Final Lua Script
Traceback (most recent call last):
  File "scripts/main.py", line 593, in <module>
    ecmo.analyze()
  File "scripts/main.py", line 584, in analyze
    self.post_init()
  File "scripts/main.py", line 542, in post_init
    self.generate_final_lua_script()
  File "scripts/main.py", line 294, in generate_final_lua_script
    print("init_irq_pointer:",hex(self.init_irq_pointer))
TypeError: 'NoneType' object cannot be interpreted as an integer

it seems the init_irq_pointer is None，how should I deal with this situation?

**Comment by YuanGao19** [comment]
How is it that under luaqemu/arm-softmmu/qemu-system-arm does not exist? Do you have any idea?

**Comment by cyruscyliu** [comment]
I think you have to build the luaqemu first. I tried this on my Ubuntu 20.04.

```
sudo apt-get install luajit libluajit-5.1-dev

cd luaqemu/
git submodule update --init dtc
chmod +x configure 
./configure  --enable-luajit --target-list=arm-softmmu --python=/usr/bin/python3
make -j4
```

**Comment by cyruscyliu** [comment]
I have the same issue.

Before running `python3 scripts/main.py configs/oxnas.cfg`,
I can boot the kernel with the original `scripts/oxnas_test.lua`

```
luaqemu/arm-softmmu/qemu-system-arm -kernel images/oxnas_zImage -M luaarm -nographic -m 4G -lua scripts/oxnas_test.lua -dtb dtbs/oxnas_test.dtb -initrd rootfs/armel.cpio.rootfs -append "console=ttyS0 nowatchdog nokaslr"
```

After running `python3 scripts/main.py configs/oxnas.cfg`,
the `scripts/oxnas_test.lua` changes. Here is the diff.

```
diff --git a/scripts/oxnas_test.lua b/scripts/oxnas_test.lua
index 806d08ac..2b298893 100644
--- a/scripts/oxnas_test.lua
+++ b/scripts/oxnas_test.lua
@@ -46,13 +46,6 @@ function dump_mem_0x8000_0x450000()
 end
 
 function change_pointers()
-       lua_write_dword(0xc03c6f50,0xd0000884)
-       lua_write_dword(0xd0010000,0xd0010004)
-       lua_write_dword(0xd0010004,1)
-       lua_write_dword(0xc03c6f54,0xd0000bcc)
-       lua_write_dword(0xc03c6f24,0)
-       lua_write_dword(0xc03c6f28,0)
-       lua_write_dword(0xc03c6f2c,0)
        lua_write_dword(0xd0001080,0)
        lua_write_dword(0xd0001084,0)
        lua_write_dword(0xd0001088,0)
@@ -141,7 +134,7 @@ end
 
 
 breakpoints = {
-       [0xc03ada08] = change_pointers,
+       [0x81732c] = dump_mem_0x8000_0x450000,
     -- early patch so that tee os can continue run
 }
 
@@ -200,6 +193,5 @@ function add_region(addr, range)
 end
 
 function post_init()
-       lua_load_file("ventilator/3.x/core_extern_oxnas.o",0xd0000000)
        lua_init_ic_timer_uart(0x44200000,0,13)
 end
```

Hope this can help to debug this problem.

**Comment by YuanGao19** [comment]
Thank you so much! That's marvelous. My problem is solved. For newbies, it is difficult to run the method successfully if the environment configuration isn't fully explained or provided in the repository. I tried to follow the author's readme in luaqemu but failed. I didn't expect to use luajit the other day, but installed lua-5.2.3 from source. 
Thanks again for the help!
